### ISSUE TITLE
Support static (named) network namespaces

### ISSUE THREAD

**Issue by phantomcraft** [stevenengler/socksns#100]
It would be a good idea the support for named namespaces (that created by $ ip netns add <some_ns>).

Two or more programs could use the same network stack.

Obviously this require root privileges.

**Comment by stevenengler** [comment]
I'm re-opening this since I think it would be useful, although I don't have any plans to work on it at the moment.

I think in general it would be useful as a way of providing the same "proxy bypass" protection for rootless docker/podman containers. You could create and run a no-network container, then start socksns with the namespace path so that the container could make external requests only through the socks port.

**Comment by stevenengler** [comment]
> It would be a good idea the support for named namespaces (that created by $ ip netns add <some_ns>).

I've added the `--netns` option in 47a479f, which I think should cover this (for example `socksns --netns /var/run/netns/<some_ns>`).

@phantomcraft It's been a while and you probably don't use this anymore, but if you do, please let me know if this new option doesn't work for you.
