### ISSUE TITLE
Feature Request: Let port be specified as a parameter

### ISSUE THREAD

**Issue by tsjk** [stevenengler/socksns#49]
I  just created an ebuild for this and installed it on my Gentoo system.
I think that is could be useful for not only tor, and also for tor socks servers running on other ports than 9050.
However, for this use case to be really nice it'd be great to be able to set the port on which the socks proxy is listening with a parameter.

**Comment by stevenengler** [comment]
I agree, I currently have two local branches, the first which adds cli options for things like setting the port, and the second which adds optional support to run as a transparent proxy (no torsocks required). The problem is that I haven't found a nice way to combine those two features. But if people are using socksns, I'll try to add the cli option parsing soon and leave the transparent proxy for a later version.

**Comment by stevenengler** [comment]
This is finally supported as of 567df22bf89. I'll make a new release for this feature soon.
